---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copyparty
data:
  copyparty.conf: |
    [global]
      e2dsa  # enable file indexing and filesystem scanning
      e2ts   # enable multimedia indexing
      ansi   # enable colors in log messages

      # q, lo: /cfg/log/%Y-%m%d.log   # log to file instead of docker

      # p: 3939          # listen on another port
      # ipa: 10.89.      # only allow connections from 10.89.*
      # df: 16           # stop accepting uploads if less than 16 GB free disk space
      # ver              # show copyparty version in the controlpanel
      # grid             # show thumbnails/grid-view by default
      # theme: 2         # monokai
      # name: datasaver  # change the server-name that's displayed in the browser
      # stats, nos-dup   # enable the prometheus endpoint, but disable the dupes counter (too slow)
      # no-robots, force-js  # make it harder for search engines to read your server


    [accounts]
      ed: wark  # username: password


    [/]            # create a volume at "/" (the webroot), which will
      /w           # share /w (the docker data volume)
      accs:
        rw: *      # everyone gets read-write access, but
        rwmda: ed  # the user "ed" gets read-write-move-delete-admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty
  labels:
    app: copyparty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: copyparty
spec:
  containers:
  - name: copyparty
    image: copyparty/ac@sha256:a24cf41d41b333bb5e51bcd19bd9e4e4722e66446a2d2253e6e3987ca20f44ca
    ports:
    - containerPort: 3923
      hostPort: 3923
    volumeMounts:
    - name: copyparty
      mountPath: /w
    - name: config
      mountPath: /cfg
  volumes:
  - name: copyparty
    persistentVolumeClaim:
      claimName: copyparty
  - name: config
    configMap:
      name: copyparty
